[project]
name = "visualens"
version = "0.1.6"
authors = [
  { name="Tom Resseguier", email="tresseg1@jhu.edu" },
]
description = "A visual interface to explore and manipulate astronomical images, catalogs, and lens models created using Lenstool."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "numpy>=1.21",
  "astropy>=5.0",
  "matplotlib>=3.5",
  "PyQt5>=5.15",
  "pyqtgraph>=0.12",
  "scipy>=1.7",
  "pandas>=1.4",
  "tqdm>=4.60",
  "corner>=2.2",
  "lenstronomy>=1.1",
  "reproject",
]

[project.urls]
"Homepage" = "https://github.com/tomresseguier/Lenstool_GUI/"
"Issues" = "https://github.com/tomresseguier/Lenstool_GUI/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
